[package]
name = "rpg_tournament"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14", features = ["dynamic_linking"] }
bitflags = "2.6.0"
extension-trait = "1.0.2"
rand = "0.8.5"
smallvec = "1.13.2"
thiserror = "1.0.63"
tiled-parser = { git="https://github.com/Anti-Alias/tiled-parser.git", default-features = false, features=["flate2"], branch="master" }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
